name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies on Ubuntu
        if: runner.os == 'Linux'
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Install dependencies on macOS
        if: runner.os == 'macOS'
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Install dependencies on Windows
        if: runner.os == 'Windows'
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
          pip install pywin32==306

      - name: List all files and their paths on Ubuntu and macOS
        if: runner.os != 'Windows'
        run: find . -type f

      - name: List all files and their paths on Windows
        if: runner.os == 'Windows'
        run: Get-ChildItem -Recurse | ForEach-Object { $_.FullName }

      - name: Build executable on Ubuntu
        if: runner.os == 'Linux'
        run: |
          pyinstaller gui.spec

      - name: Build executable on macOS
        if: runner.os == 'macOS'
        run: |
          pyinstaller gui.spec

      - name: Build executable on Windows
        if: runner.os == 'Windows'
        run: |
          pyinstaller gui.spec

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts-${{ matrix.os }}
          path: dist/
