name: Build and Create Installer for Windows

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m venv venv
        .\venv\Scripts\activate
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: |
        .\venv\Scripts\activate
        pip install pyinstaller

    - name: Build executable
      run: |
        .\venv\Scripts\activate
        pyinstaller --onefile --windowed --name popmart gui.spec

    - name: Download and install Inno Setup
      run: choco install -y innosetup

    - name: Create Inno Setup installer
      run: C:\Program Files (x86)\Inno Setup 6\ISCC.exe setup.iss

    - name: Archive installer
      uses: actions/upload-artifact@v2
      with:
        name: windows-installer
        path: ./PopmartBotInstaller.exe
